language: clojure
lein: lein
dist: trusty

script: lein with-profile -dev,+ci do clean, compile :all, test, doo phantom test once

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk11
